### ISSUE TITLE
Add whether it's a subworkflow to the workflow finished event

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/go-workflows#135]
Add a tag whether a finished workflow is a sub-workflow or not

**Comment by zaataylor** [comment]
For my own understanding before I try to pick it up, is this now handled by this logic? Or is there still more to do? https://github.com/cschleiden/go-workflows/blob/ee044bf23ee14e0091dedae05e0842b55eec5c73/internal/worker/workflow.go#L147-L152

**Comment by cschleiden** [comment]
Oh it looks like it 😄
