### ISSUE TITLE
For slow workflow tasks without heartbeats, abandoning workflow task events can crash the engine

### ISSUE THREAD

**Issue by yaananth** [cschleiden/go-workflows#144]
If we have a workflow task executing more than default execution time  (default is [1 min](https://github.com/cschleiden/go-workflows/blob/c7407721e676674611c5b5c1a451dd4fae805a8b/backend/options.go#L29))....

The redis backend for example, [enqueues a task if it's abandoned](https://github.com/cschleiden/go-workflows/blob/c7407721e676674611c5b5c1a451dd4fae805a8b/backend/redis/queue.go#L107)

So, we have one executing for more than a minute, the backend saw that being timed out (since by default we don't have heartbeat) and enqueued the same task. Now we have two running the same thing!

Both will share the same [**cache**](https://github.com/search?q=repo%3Acschleiden%2Fgo-workflows%20NewWorkflowExecutorLRUCache&type=code), so one would be stepping on to another.

One example of this is, imagine the first one finished activity, the second one tries to do the same, we would hit:

The error `could not find pending future for activity completion` is from [`executor.go`](https://github.com/cschleiden/go-workflows/blob/c7407721e676674611c5b5c1a451dd4fae805a8b/internal/workflow/executor.go#L370)

But, it's not just that, we will crash because of that.

That's because we [fail to replay history ](https://github.com/cschleiden/go-workflows/blob/c7407721e676674611c5b5c1a451dd4fae805a8b/internal/workflow/executor.go#L138)and return `nil`, that ends up crashing the engine.

So few things:

- [ ] Should we band-aid fix it so we will auto-recover in cases, by ignoring the duplicate task or forcing a heartbeat?
- [ ] We should at least handle the situation so that we don't crash the engine

**Comment by cschleiden** [comment]
As an immediate work-around I'd encourage enabling workflow heartbeats, they'd keep the task assigned to the current worker and prevent this from happening. 

In addition it would be good to detect this and at least not break. Potentially by locking the workflow instance on the worker to ensure it's not executing the same task twice 🤔

**Comment by cschleiden** [comment]
The default heartbeat has been set to 25s a while ago, closing this for now.
