### ISSUE TITLE
Prevent early workflow exit when subworkflow completes

### ISSUE THREAD

**Issue by zaataylor** [cschleiden/go-workflows#149]
# Description
I think I've found an interesting bug related to workflow completion when subworkflows are signaled in a certain order. I have a minimal working example in the form of a test at: https://github.com/zaataylor/go-workflows/blob/253ce2d645263b21bda0df1452ef8c13ef075ff4/tester/tester_test.go#L240

# Reproducing the Issue
1. Comment out https://github.com/zaataylor/go-workflows/blob/253ce2d645263b21bda0df1452ef8c13ef075ff4/tester/tester.go#L294-L309
2. Run the `Test_WorkflowProperExitAfterSignallingMultipleSubWorkflows` test

# My Initial Investigation
## The Error
This issue was initially observed in production code after running tests on a more complex workflow set up similarly to the example included on the branch above. The error we saw when running our tests (edited to add spacing for clarity) was:

```
panic: could not convert workflow result to expected type json: cannot unmarshal object into Go value of type result.Conclusion [recovered]
	panic: could not convert workflow result to expected type
               json: cannot unmarshal object into Go value of type result.Conclusion

goroutine 19 [running]:
testing.tRunner.func1.2({0xb4bf00, 0xc0005241e0})
	/usr/local/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1399 +0x39f
panic({0xb4bf00, 0xc0005241e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/cschleiden/go-workflows/tester.(*workflowTester[...]).WorkflowResult(0xc0004e8000)
	/workspaces/***/vendor/github.com/cschleiden/go-workflows/tester/tester.go:414 +0xcb
github.com/github/***/orchestration/workflows.TestExecutePlanBasicCancellations.func1(0x1?)
	/workspaces/***/orchestration/workflows/executeplan_test.go:114 +0x3b6
testing.tRunner(0xc0004a24e0, 0xc0004b0048)
	/usr/local/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x35f
FAIL	github.com/github/***/***/workflows	0.190s
FAIL
```

It turns out what was happening here is that our top-level workflow, which was initialized in the tester as having a result of type `result.Conclusion`, was receiving a result that was actually a `JobFactoryResult`, which is a Go object. `go-workflows` was attempting to convert a struct of form:
```golang
type JobFactoryResult struct {
   Conclusion: result.Conclusion
   Reason: string
}
```

into `result.Conclusion`, leading to the error mentioned above.

## Why is this happening?
Our top-level workflow creates a subworkflow called `ExecuteJobFactory`. This subworkflow's return type is `JobFactoryResult`. The starting/initial/top-level workflow is exiting when the `ExecuteJobFactory` _subworkflow_ returns, which is causing it to receive a workflow result of type `JobFactoryResult`.

## Why is _that_ happening?
It appears that in the `go-workflows` tester at the point where the subworkflow finishes execution and the tester is processing a `WorkflowExecutionFinished` event at https://github.com/cschleiden/go-workflows/blob/af7b6ed230c91c001cd6a8bd3bdc5dd4fc5d8861/tester/tester.go#L277-L281
```golang
if !tw.instance.SubWorkflow() {
	wt.workflowFinished = true
	wt.workflowResult = a.Result
	wt.workflowErr = a.Error
}
```

`tw.instance.ParentInstanceID == ""`, which causes `tw.instance.SubWorkflow()` to return `false`, meaning that tester thinks the finished subworkflow is not actually a subworkflow. Thus, it doesn't continue processing events, and simply thinks the overall workflow is finished.

## (Why is _that_ happening?)<sup>2</sup>
It has something to do with how the tester adds new workflow instances when subworkflows are scheduled and signals are received for them. I don't understand the exact sequence _perfectly_, nor the reason why this issue only seems to have appeared with some of our recent changes. It requires more investigation to understand the exact connection, but I think I have an idea of a fix nonetheless.

## What's the fix?
We need some way of ensuring that `WorkflowInstance` state created by the tester remains consistent as new events occur to ensure that instances which are subworkflows are properly labeled as that (by having non-empty `ParentInstanceID`s and accurate `ParentEventID`s, too). The actual changes likely aren't _too_ involved and I have an example fix in the repro branch I mentioned.

**Comment by cschleiden** [comment]
Thanks for this report. The root cause here is that the subworkflow instance is signaled _before_ it's scheduled/created. And  since we don't have the full `Instance` when signaling, that event is used to create the subworkflow instance and the tester records it only with its incomplete ID. 

I think it's time to go back and change how other workflows are signaled from within workflows.
