### ISSUE TITLE
Postgres/CRDB backend

### ISSUE THREAD

**Issue by danthegoodman1** [cschleiden/go-workflows#199]
I'm very interested in (and potentially contributing) a Postgres protocol supported backend. I would intend to be running on CockroachDB specifically, so I'd Iam to avoid postgres-only data types, function languages, etc.

**Comment by cschleiden** [comment]
@cbsmith402 wrote a Postgres backend here: https://github.com/cschleiden/go-workflows/pull/140 

I wasn't able to accept the contribution into this repo though, I want to keep the number of "core" backends somewhat small to make it easier for me to make changes. But still happy to link to any separate repo.

**Comment by danthegoodman1** [comment]
@cschleiden are there any docs on how to load it in as an external backend?

**Comment by cschleiden** [comment]
@danthegoodman1 not really, but the only requirement is to implement the `backend.Backend` interface and then pass an instance to the client and worker.
