### ISSUE TITLE
the interval for workflow is way longer than I defined after executing for a long time

### ISSUE THREAD

**Issue by xdc0527** [cschleiden/go-workflows#208]
I use the DefaultRetryOptions which BackoffCoefficient is 1, so I should expect a constant interval, but the interval between workflow task is way longer than beginning after executing for a long time, do you know why this occur and how to fix it?

**Comment by xdc0527** [comment]
![image](https://github.com/cschleiden/go-workflows/assets/58333876/24ee4363-866a-4e98-81a2-0c304d4e73e2)

**Comment by xdc0527** [comment]
@cschleiden

**Comment by cschleiden** [comment]
Could you share the relevant part of your workflow? And does that only show in the UI or do you also observe it in the logs/when debugging?
