### ISSUE TITLE
The multi-instance  workflows executing occur "previous workflow execution scheduled different type of activity"

### ISSUE THREAD

**Issue by Robinmxc** [cschleiden/go-workflows#214]
Our application integrates workflow and is deployed with multiple instances. However, this error occurred recently.
![image](https://github.com/cschleiden/go-workflows/assets/70931102/f111cfa3-c26f-46b0-a67a-440b79cae7d6)
![image](https://github.com/cschleiden/go-workflows/assets/70931102/43772cee-a342-4800-92b3-e1c110f7ebf8)

I have read some of the source code and found that the generation of scheduleEventID may be the cause of this problem.

func (wf *WfState) GetNextScheduleEventID() int64 {
	scheduleEventID := wf.scheduleEventID
	wf.scheduleEventID++
	return scheduleEventID
}

Because we are deploying multiple instances, it may not result in all scheduleEventIDs being generated within the same instance. Therefore, I would like to ask if workflow does not support multiple instances.

**Comment by cschleiden** [comment]
Only a single executor should work on a task and an instance at a time, so there shouldn't be any conflicts. All of the events having the same `#420` sequence ID looks suspicious to me. What backend are you using?

**Comment by cschleiden** [comment]
Are you able to create a minimal repro or share relevant parts of your code?
