### ISSUE TITLE
how can I wait certain amount of time between two activies

### ISSUE THREAD

**Issue by xdc0527** [cschleiden/go-workflows#223]
I use time.Sleep() which will cause workflow to panic because of deadlock detection and workflow.Sleep() also fails. I also tried workflow.Await(workflow.ScheduleTimer()), but I also fails with error "previous workflow execution scheduled an activity, not: ScheduleTimer". Is there a way to achieve this?

**Comment by xdc0527** [comment]
@cschleiden

**Comment by cschleiden** [comment]
you should use `workflow.Sleep()`. What do you mean, "it fails"?

**Comment by xdc0527** [comment]
It also returns previous workflow execution scheduled an activity, not: ScheduleTimer" for workflow.Sleep()

**Comment by xdc0527** [comment]
I refactor the code and remove normal function execution after workflow.Sleep() and only put it between two activities, the previous error does not show, but another error occurs: "previous workflow execution scheduled different type of activity"

**Comment by xdc0527** [comment]
@cschleiden

**Comment by xdc0527** [comment]
> I refactor the code and remove normal function execution after workflow.Sleep() and only put it between two activities, the previous error does not show, but another error occurs: "previous workflow execution scheduled different type of activity"

This happen because I put workflow.Sleep() between normal function execution and activity

**Comment by xdc0527** [comment]
> It also returns previous workflow execution scheduled an activity, not: ScheduleTimer" for workflow.Sleep()

This happen because I put workflow.Sleep() between two normal function executions

**Comment by xdc0527** [comment]
If I put workflow.Sleep() between two activities, it works fine, I wonder why above two will fail

**Comment by cschleiden** [comment]
I'm still not quite sure what you mean. Could you provide some code or a repo that illustrates the problem?
