### ISSUE TITLE
Allow namespacing workflows

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/go-workflows#224]
- [ ] Include namespaces in metrics as tags
- [ ] Reserve an internal namespace
- [ ] Move internal activities like sending a signal to an internal namespace
- [ ] Allow namespace selection in diag UI

**Comment by decibelcooper** [comment]
If workflows can reference alternate namespaces for subworkflows and activities, that would add a lot of power that seems to be missing for separating concerns among workers.

**Comment by cschleiden** [comment]
With #245 this should be easier to implement.

**Comment by cschleiden** [comment]
Closing in favor of: https://github.com/cschleiden/go-workflows/issues/349
