### ISSUE TITLE
Add a RedisBackendOption to prefix all keys with a certain string

### ISSUE THREAD

**Issue by thielepaul** [cschleiden/go-workflows#227]
If the redis instance that is used as a backend for go-workflows is also used for other things, it would be useful to have a `RedisBackendOption` that allows to prefix all keys in `backend/redis/keys.go` and `backend/redis/queue.go` with a custom string.

E.g. instead of `instances-active` -> `my-workflow:instances-active`

**Comment by cschleiden** [comment]
Closing as not planned for now.
