### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by lovromazgon** [cschleiden/go-workflows#237]
I noticed that running an _idle worker_ consumes a lot of CPU, my activity monitor consistently shows ~170% CPU usage (at least with the sqlite backend, I didn't try other backends). I figured out that the culprits are the pollers which continuously poll the backend for new workflow and activity instances, specifically these functions:
- https://github.com/cschleiden/go-workflows/blob/main/internal/worker/workflow.go#L84
- https://github.com/cschleiden/go-workflows/blob/main/internal/worker/activity.go#L72

What do you think about adding a ticker instead of the `default` case and making the polling rate configurable? I am happy to open a PR for this.

**Comment by cschleiden** [comment]
I think in general that makes a lot of sense. The only thing to keep in mind are backend implementations like the current Redis one, where the `GetWorkflowTask` function blocks and we _do_ want to call that as quickly as possible after receiving a task. I wouldn't want an additional delay there.

Maybe a backend option to specify the polling rate and the implementation can decide to ignore that and instruct the workers to poll as quickly as possible.

**Comment by lovromazgon** [comment]
I created a PR and added the options to the worker options instead of backend, since it seems that the polling interval is more connected to the worker than to the backend (e.g. maybe one worker needs to poll more often than another). The backend can still overwrite this behavior by implementing `worker.BlockingBackend`, then the old behavior will be selected (continuous calls to get new tasks).

**Comment by vroldanbet** [comment]
+1 noticed this too when running on a similar setup

**Comment by cschleiden** [comment]
Thanks for the quick turnaround! PR looks good to me, going to merge once checks are finished 👍
