### ISSUE TITLE
Support database migrations

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/go-workflows#244]
Support migrations for the sqlite and mysql database schemas.

**Comment by decibelcooper** [comment]
question: is there an opportunity for Backend-agnostic migrations, supporting a kind of an ORM migration approach?

E.g., today there is a `diag.Backend` interface for inspecting data from supporting `backend.Backend`s for diagnostic purposes.  Perhaps a similar interface could support Backend-agnostic migrations.
