### ISSUE TITLE
Prevent creating multiple workflow instances with the same instance id

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/go-workflows#260]
Two subsequent `CreateWorkflowInstance` calls with the same id should result in an error.

_Discussed in https://github.com/cschleiden/go-workflows/discussions/259_

**Comment by decibelcooper** [comment]
thought: perhaps it's best to follow Temporal's lead and allow the user to set an ID reuse policy

A simplified binary allow/reject duplicate option should satisfy most use cases.  Could probably simply be used as a hint for whether or not to generate a random execution ID?  Or would it be reasonable to expose the execution ID to the client API?

**Comment by lyuboxa** [comment]
When I encountered this first, I looked at the potential options to enable some uniqueness in the schema without interfering too much with the codebase. Unfortunately, making instance id unique individually has implications for functionalities like `ContinueAsNew` where the instance id is reused with an updated execution id. This can be addressed
in code though with some safety from the database.

This led me to think that decoupling instance definition and execution may provide more flexibility.

> thought: perhaps it's best to follow Temporal's lead and allow the user to set an ID reuse policy

The reuse policy definition is a good way to provide optionality, 👍

**Comment by cschleiden** [comment]
> Today, the behavior for signaling instances with multiple active executions is undefined at the Backend level. Looking anecdotally at the mysql backend, I see that we just snag one execution to signal. It might be reasonable to instead perform a broadcast of sorts, so that all active executions receive the signal.

There should only be one active execution at any point in time. If there are multiple, that's a bug and not as designed.

**Comment by cschleiden** [comment]
Closed in #288
