### ISSUE TITLE
Pagination not working in diag UI

### ISSUE THREAD

**Issue by cspotcode** [cschleiden/go-workflows#343]
Is this a known issue? Page 1 populates with the most recent workflows, but page 2 is always empty.

I'm using the mysql backend, would this be a bug in the query that skips the first page w/`#/?after=`?

![image](https://github.com/cschleiden/go-workflows/assets/376504/8c7133d5-f2b0-4768-874d-77fb99faa805)

**Comment by cschleiden** [comment]
Thanks for the report, fix should go in shortly 🙇
