### ISSUE TITLE
Investigate whether to adopt `iter` package

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/go-workflows#352]
Can we use `iter` - https://github.com/golang/go/issues/61897 for the coroutine functionality at the base of the executor?

**Comment by valyala** [comment]
[This article](https://valyala.medium.com/go-evolves-in-the-wrong-direction-7dfda8a1a620) may be useful during the investigation.

**Comment by cschleiden** [comment]
@valyala that's what led me to create this issue 😄

**Comment by cschleiden** [comment]
Closing this for now.
