### ISSUE TITLE
How to get the workflow version?

### ISSUE THREAD

**Issue by rullyalves** [cschleiden/go-workflows#355]
In the documentation it says that I can get the workflow version with:
workflow.Version, but I checked the package and this function is not available

documentation link: 
https://cschleiden.github.io/go-workflows/#workflow-versioning

**Comment by cschleiden** [comment]
This is not supported:

> Therefore for now versioning is not supported and the guidance is to rely on side-by-side deployments.

You pass in a version yourself as a parameter or you context propagation if you want this to be passed to sub-workflows etc.

**Comment by rullyalves** [comment]
is there any way like:
pass the version parameter to the workflow when running and check a service for the current version and use something like "ContinueAsNew" to update the workflow with the new history?

I thought about doing this to enable migrations without filling the code with if/else conditions, would it be viable to use continueAsNew for this? Or would it be best to keep previous versions of activities/workflows?

My fear is having many coexisting versions, I would also like to know if there is a way to know how many pending tasks there are for a workflow and perform a possible migration of that
