### ISSUE TITLE
How set a timeout so that a activity task execution becomes stale

### ISSUE THREAD

**Issue by rullyalves** [cschleiden/go-workflows#358]
there are use cases where a workflow can be started, paused for a long time and then resume execution, if an activity calculates a volatile value, such as a user's account balance, is there any way to restart the workflow if it takes a long time to execute? I thought about using "continueAsNew" for this, but it would restart the entire workflow and not just specific activities

It could be interesting to allow a parameter or a timeout where after resuming workflow execution, certain tasks become "stale" and are recalculated

If this change makes sense, I would like to try to contribute a PR to support this use case

**Comment by cschleiden** [comment]
I think you also asked about this in a discussion? I'm not quite sure about the scenario. 

You could manually keep the timestamp together with the calculcation result from your activity. Then, once your workflow resumes and the value is too old you can recompute it.
