### ISSUE TITLE
Expose workflow and activity "call stack" information from `ctx`.

### ISSUE THREAD

**Issue by aybabtme** [cschleiden/go-workflows#82]
For telemetry purpose, it's useful to have access to the current "call stack" of workflow, sub workflow, activities and so on, at any given point. For instance, to make better error messages, to annotate alerts to Sentry, to log them (already built in), to trace, to.... whatever else you might want to do with this.

It would be great if you could extract this from both a `context.Context` and a `workflow.Context`, and if the human friendly name of things was included (not just the IDs).

**Comment by cschleiden** [comment]
Closing this for now as not planned.
