### ISSUE TITLE
Allow passing in custom `Converter` instances

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/go-workflows#84]
Currently all workflow/activity arguments and results are marshaled using `encoding/json`. It should be possible to use custom converters to, for example, support binary formats.

**Comment by zaataylor** [comment]
This is an interesting idea I also stumbled upon while looking at some of the original converter code! Specifically, I was thinking about a Protobuf serialization use case and wondering how I might use something like `encoding/protojson` instead of the default `encoding/json`.
